copyLogInfo: copy queue information to avoid SEGV
logrotate might crash when using invalid configuration settings in combination with include

example configuration:

    /tmp/logsegv/segv.log {
      include /tmp/logsegv/segv.cfg

      "" {

      }
    }

will lead to

    $ ./logrotate -vfd -s /tmp/logsegv/segv.state /tmp/logsegv/segv.cfg
    WARNING: logrotate in debug mode does nothing except printing debug messages!  Consider using verbose mode (-v) instead if this is not what you want.

    reading config file /tmp/logsegv/segv.cfg
    including /tmp/logsegv/segv.cfg
    reading config file /tmp/logsegv/segv.cfg
    error: /tmp/logsegv/segv.cfg:1 duplicate log entry for /tmp/logsegv/segv.log
    including /tmp/logsegv/segv.cfg
    reading config file /tmp/logsegv/segv.cfg
    error: /tmp/logsegv/segv.cfg:1 duplicate log entry for /tmp/logsegv/segv.log
    including /tmp/logsegv/segv.cfg
    reading config file /tmp/logsegv/segv.cfg
    error: /tmp/logsegv/segv.cfg:1 duplicate log entry for /tmp/logsegv/segv.log
    including /tmp/logsegv/segv.cfg
    reading config file /tmp/logsegv/segv.cfg
    error: /tmp/logsegv/segv.cfg:1 duplicate log entry for /tmp/logsegv/segv.log
    including /tmp/logsegv/segv.cfg
    reading config file /tmp/logsegv/segv.cfg
    error: /tmp/logsegv/segv.cfg:1 duplicate log entry for /tmp/logsegv/segv.log
    including /tmp/logsegv/segv.cfg
    reading config file /tmp/logsegv/segv.cfg
    error: /tmp/logsegv/segv.cfg:1 duplicate log entry for /tmp/logsegv/segv.log
    including /tmp/logsegv/segv.cfg
    reading config file /tmp/logsegv/segv.cfg
    error: /tmp/logsegv/segv.cfg:1 duplicate log entry for /tmp/logsegv/segv.log
    including /tmp/logsegv/segv.cfg
    reading config file /tmp/logsegv/segv.cfg
    error: /tmp/logsegv/segv.cfg:1 duplicate log entry for /tmp/logsegv/segv.log
    including /tmp/logsegv/segv.cfg
    reading config file /tmp/logsegv/segv.cfg
    error: /tmp/logsegv/segv.cfg:1 duplicate log entry for /tmp/logsegv/segv.log
    including /tmp/logsegv/segv.cfg
    reading config file /tmp/logsegv/segv.cfg
    error: /tmp/logsegv/segv.cfg:1 duplicate log entry for /tmp/logsegv/segv.log
    including /tmp/logsegv/segv.cfg
    reading config file /tmp/logsegv/segv.cfg
    error: /tmp/logsegv/segv.cfg:1 duplicate log entry for /tmp/logsegv/segv.log
    including /tmp/logsegv/segv.cfg
    reading config file /tmp/logsegv/segv.cfg
    error: /tmp/logsegv/segv.cfg:1 duplicate log entry for /tmp/logsegv/segv.log
    including /tmp/logsegv/segv.cfg
    reading config file /tmp/logsegv/segv.cfg
    error: /tmp/logsegv/segv.cfg:1 duplicate log entry for /tmp/logsegv/segv.log
    including /tmp/logsegv/segv.cfg
    reading config file /tmp/logsegv/segv.cfg
    error: /tmp/logsegv/segv.cfg:1 duplicate log entry for /tmp/logsegv/segv.log
    including /tmp/logsegv/segv.cfg
    reading config file /tmp/logsegv/segv.cfg
    error: /tmp/logsegv/segv.cfg:1 duplicate log entry for /tmp/logsegv/segv.log
    including /tmp/logsegv/segv.cfg
    reading config file /tmp/logsegv/segv.cfg
    error: /tmp/logsegv/segv.cfg:1 duplicate log entry for /tmp/logsegv/segv.log
    including /tmp/logsegv/segv.cfg
    error: /tmp/logsegv/segv.cfg:2 include nesting too deep
    error: /tmp/logsegv/segv.cfg:4 unexpected log filename
    error: found error in /tmp/logsegv/segv.log , skipping
    removing last 1 log configs
    error: /tmp/logsegv/segv.cfg:4 unexpected log filename
    error: found error in log config, skipping
    removing last 1 log configs
    config.c:553:23: runtime error: load of null pointer of type 'struct logInfo *'
    SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior config.c:553:23 in
    AddressSanitizer:DEADLYSIGNAL
    =================================================================
    ==12601==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0000004d79a1 bp 0x7ffca98d0c30 sp 0x7ffca98d0c10 T0)
    ==12601==The signal is caused by a READ memory access.
    ==12601==Hint: address points to the zero page.
      #0 0x4d79a0 in freeTailLogs logrotate/config.c:553:23
      #1 0x4cb482 in readConfigFile logrotate/config.c:1870:21
      #2 0x4c78fc in readConfigPath logrotate/config.c:685:13
      #3 0x4d164c in readConfigFile logrotate/config.c:1457:30
      #4 0x4c78fc in readConfigPath logrotate/config.c:685:13
      #5 0x4d164c in readConfigFile logrotate/config.c:1457:30
      #6 0x4c78fc in readConfigPath logrotate/config.c:685:13
      #7 0x4d164c in readConfigFile logrotate/config.c:1457:30
      #8 0x4c78fc in readConfigPath logrotate/config.c:685:13
      #9 0x4d164c in readConfigFile logrotate/config.c:1457:30
      #10 0x4c78fc in readConfigPath logrotate/config.c:685:13
      #11 0x4d164c in readConfigFile logrotate/config.c:1457:30
      #12 0x4c78fc in readConfigPath logrotate/config.c:685:13
      #13 0x4d164c in readConfigFile logrotate/config.c:1457:30
      #14 0x4c78fc in readConfigPath logrotate/config.c:685:13
      #15 0x4d164c in readConfigFile logrotate/config.c:1457:30
      #16 0x4c78fc in readConfigPath logrotate/config.c:685:13
      #17 0x4d164c in readConfigFile logrotate/config.c:1457:30
      #18 0x4c78fc in readConfigPath logrotate/config.c:685:13
      #19 0x4d164c in readConfigFile logrotate/config.c:1457:30
      #20 0x4c78fc in readConfigPath logrotate/config.c:685:13
      #21 0x4d164c in readConfigFile logrotate/config.c:1457:30
      #22 0x4c78fc in readConfigPath logrotate/config.c:685:13
      #23 0x4d164c in readConfigFile logrotate/config.c:1457:30
      #24 0x4c78fc in readConfigPath logrotate/config.c:685:13
      #25 0x4d164c in readConfigFile logrotate/config.c:1457:30
      #26 0x4c78fc in readConfigPath logrotate/config.c:685:13
      #27 0x4d164c in readConfigFile logrotate/config.c:1457:30
      #28 0x4c78fc in readConfigPath logrotate/config.c:685:13
      #29 0x4d164c in readConfigFile logrotate/config.c:1457:30
      #30 0x4c78fc in readConfigPath logrotate/config.c:685:13
      #31 0x4d164c in readConfigFile logrotate/config.c:1457:30
      #32 0x4c78fc in readConfigPath logrotate/config.c:685:13
      #33 0x4c70bb in readAllConfigPaths logrotate/config.c:759:13
      #34 0x4d961d in main logrotate/logrotate.c:2791:9
      #35 0x7fa31d719bba in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x26bba)
      #36 0x41f7a9 in _start (logrotate/logrotate+0x41f7a9)

    AddressSanitizer can not provide additional info.
    SUMMARY: AddressSanitizer: SEGV /home/christian/Coding/workspaces/smartgit/logrotate/config.c:553:23 in freeTailLogs
    ==12601==ABORTING

Fixes: #271
Closes #272