allocateHash: fix incorrect sizeof computation (#149)
This was supposed to be fixed by 3.12.3-21-g8523cb3 but it was not
because there was a typo sizeof(sizeof ...) and even after fixing
the typo it referred to the pointer size, instead of struct size.

Luckily, this was detected by Clang analyzer again.  Now I verified
that the defect goes away with this commit:

FIXED DEFECTS
=============
Error: CLANG_WARNING:
logrotate.c:249:15: warning: Result of 'malloc' is converted to a pointer of type 'struct logStateList', which is incompatible with sizeof operand type 'unsigned long'