Do not check for null input in custom strndup implementation
The standard strndup() does expect a string (not a NULL) value.

The extra check breaks gcc-10 with lto:

    config.c: In function ‘strndup’:
    config.c:88:7: error: ‘nonnull’ argument ‘s’ compared to NULL [-Werror=nonnull-compare]
       88 |     if(!s)
          |       ^
    cc1: all warnings being treated as errors