ci: update apt metadata cache before installing deps
... to eliminate unrelated CI failures like this:
```
Run sudo apt-get install -y automake gcc-14 libacl1-dev libpopt-dev libselinux1-dev
Reading package lists...
Building dependency tree...
Reading state information...
automake is already the newest version (1:1.16.5-1.3ubuntu1).
gcc-14 is already the newest version (14.2.0-4ubuntu2~24.04.1).
gcc-14 set to manually installed.
The following NEW packages will be installed:
  libacl1-dev libattr1-dev libpopt-dev libselinux1-dev libsepol-dev
0 upgraded, 5 newly installed, 0 to remove and 1 not upgraded.
Need to get 697 kB of archives.
After this operation, 2928 kB of additional disk space will be used.
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [144 B]
Get:2 http://azure.archive.ubuntu.com/ubuntu noble/main amd64 libpopt-dev amd64 1.19+dfsg-1build1 [47.8 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu noble/main amd64 libsepol-dev amd64 3.5-2build1 [384 kB]
Get:4 http://azure.archive.ubuntu.com/ubuntu noble-updates/main amd64 libselinux1-dev amd64 3.5-2ubuntu2.1 [164 kB]
Ign:5 http://azure.archive.ubuntu.com/ubuntu noble-updates/main amd64 libattr1-dev amd64 1:2.5.2-1build1.1
Get:6 http://azure.archive.ubuntu.com/ubuntu noble-updates/main amd64 libacl1-dev amd64 2.3.2-1build1.1 [78.5 kB]
Ign:5 https://archive.ubuntu.com/ubuntu noble-updates/main amd64 libattr1-dev amd64 1:2.5.2-1build1.1
Err:5 https://security.ubuntu.com/ubuntu noble-updates/main amd64 libattr1-dev amd64 1:2.5.2-1build1.1
  404  Not Found [IP: 52.154.174.208 80]
E: Failed to fetch https://security.ubuntu.com/ubuntu/pool/main/a/attr/libattr1-dev_2.5.2-1build1.1_amd64.deb  404  Not Found [IP: 52.154.174.208 80]
Fetched 674 kB in 2s (360 kB/s)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```

Related: https://github.com/logrotate/logrotate/pull/726