switch_user_permanently: skip switchback check if switched to root
Allow switching only the real group (not the user) with a configuration
like `su root somegroup`.
E.g. mailman uses `su root list`, which currently fails with:
    error: failed to switch user permanently, able to switch back
    error: failed to compress log /var/log/mailman/qrunner.1

Fixes: a0b05e42a590efa3e575dd2001b6aa390a79c769 ("switch_user_permanently: check if switchback is possible")
Closes: https://github.com/logrotate/logrotate/pull/319