.shellcheckrc: tell ShellCheck where to look for sourced scripts
... to eliminate false positive in the Differential ShellCheck CI job:

Error: SHELLCHECK_WARNING:
./test/test-0093.sh:3:3: note[SC1091]: Not following: ./test-common.sh: openBinaryFile: does not exist (No such file or directory)