warnings: add missing poptOption initializers
The popt(3) manual instructs to define arcDescrip field as NULL when not
needed.  This fixes these warnings.

logrotate.c:2467:3: error: missing initializer for field 'argDescrip' of
'struct poptOption' [-Werror=missing-field-initializers]
   "Don't do anything, just test (implies -v)"},
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from logrotate.c:11:0:
/usr/include/popt.h:136:18: note: 'argDescrip' declared here
     const char * argDescrip; /*!< argument description for autohelp */

Signed-off-by: Sami Kerola <kerolasa@iki.fi>

Closes #98