Remove invalid configuration on error
After failing while parsing an invalid configuration file, like:

    /some/path

remove the erroneous configuration structure from the internal list.

Else one might see:

    reading config file config.tmp
    error: config.tmp:1 missing '{' after log files definition
    Reading state from file: state.tmp
    error: error opening state file state.tmp: No such file or directory
    Allocating hash table for state file, size 64 entries

    Handling 1 logs

    rotating pattern: (null) forced from command line (no old logs will be kept)
    empty log files are rotated, old logs are removed
    No logs found. Rotation not needed.