Avoid confusing error message in debug mode
In debug mode the state file is not created if not already existent in
lockState().  Do not print the message

    error: error opening state file /var/lib/logrotate.status: No such file or directory

while trying to read the state file, since in debug mode this is not an
error.

Related: #425